Spanish
syberia-project/platform_frameworks_base pull request #8
Opened 2019-02-22 14:17 UTC by David6910

2019-02-22 14:36 UTC, alexxxdev requested changes

2019-02-22 14:36 UTC, alexxxdev commented on core/res/res/values-es/syb_strings.xml
> +    <string name="privacy_guard_dialog_summary"><xliff:g id="app">%1$s</xliff:g>  le gustaria <xliff:g id="op">%2$s</xliff:g>string>
please, fix "string>"

2019-02-22 15:24 UTC, Maullame reviewed
done

2019-02-22 15:24 UTC, David6910 commented on core/res/res/values-es/syb_strings.xml
> +    <string name="privacy_guard_dialog_summary"><xliff:g id="app">%1$s</xliff:g>  le gustaria <xliff:g id="op">%2$s</xliff:g>string>
Done

2019-02-23 05:42 UTC, alexxxdev approved these changes

2019-02-23 05:43 UTC, merged